name: Node.js CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.4  # Updated to the latest version

    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          # Ensure the directory exists
          mkdir -p /apps/ci-cd
          cd /apps/ci-cd
          
          # Check if it's a git repository
          if [ ! -d ".git" ]; then
            git init
            git remote add origin https://github.com/ilg0rbek/ci-cd.git
          fi
          
          git pull origin main
          npm install
          pm2 restart 0 || pm2 start index.js
